# Generated by Django 3.2.13 on 2022-09-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_shop', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
