# Generated by Django 3.2.13 on 2022-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_shop', '0007_auto_20220930_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='fuel_delivery',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='gears',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='height',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='length',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='width',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
