# Generated by Django 3.2.13 on 2022-10-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_shop', '0008_auto_20221003_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image5',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
