# Generated by Django 3.2.13 on 2022-10-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_shop', '0011_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
